spring:
  application:
    name: catalog-service
  #컨피그 서비스에서 설정을 가져올 것을 카탈로그 서비스에 지시
  config:
    import: "optional:configserver:" #가능하면 컨피그 서버에서 설정 데이터를 가져온다.
  cloud:
    config:
      uri: http://localhost:8888 #설정 서버의 URL
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
  threads:
    max: 50
    min-spare: 5

polar:
  greeting: Welcome to the local book catalog!